# This code is used to convert the talks data frame generated by build_full_schedule.R
# to flat files for each day in a format that can be used to create Excel sheets
# with embedded hyperlinks to each talk

# Load libraries
library(lubridate)
library(dplyr)
library(tidyr)
library(stringr)

# Source functions
source("functions/process_talks.R")
source("functions/order_rooms.R")

# Import AFS talks and format date and datetime
talks <- read.csv("afs_talks.csv") %>%
  mutate(date = ymd(date),
         datetime = ymd_hms(datetime))

# For each date (Sept 30 to Oct 3)
# filter and reshape data using process_table()
# reorder columns based on order_rooms()
# export as .csv
for(i in as.character(unique(talks$date))) {
  process_talks(i) %>%
    select(Time, order_rooms(.)) %>%
    write.csv(paste0("talks_", as.character(i), ".csv"), row.names = FALSE)
}
